### ISSUE TITLE
The 'run' method seems sometimes to take arguments

### ISSUE THREAD

**Issue by OriPekelman** [af83/sponges#1]
Based on the example code, I got the following error intermittantly:

```
`run': wrong number of arguments (1 for 0) (ArgumentError)
```

and then, when I add an argument to the method definition I may get

```
`run': wrong number of arguments (0 for 1) (ArgumentError)
```

Seems to have something to do with config.worker_args   = {first: true}   ?
what gives?

**Comment by oz** [comment]
@OriPekelman care to provide some context here? I'm not sure what is it that you're asking at all. ^^;

**Comment by chatgris** [comment]
@OriPekelman I am working on a refactoring that will bring more flexibility. Check out [this commit](https://github.com/AF83/sponges/commit/c3804070c7256b837b41de23cd08183c659a730e).

**Comment by OriPekelman** [comment]
oops should have read the "run" methods, correcting title..

**Comment by chatgris** [comment]
The `pids` and the `pids_with_args` examples are both named "bob". If both of them are running at the same time, that could explain this case.

**Comment by chatgris** [comment]
I was not able to reproduce this behavior. :neutral_face:

A full  stacktrace would be welcomed.
