### ISSUE TITLE
find_supervisor glitchy on osx

### ISSUE THREAD

**Issue by piotrb** [af83/sponges#4]
For some reason on osx Sys::ProcTable seems to return a space padded string for the cmdline. ie: 

`"foo_bar_supervisor  "`

Not sure how widespread this is .. but the whole test suite for sponges seems to hate the world on osx (every test failing because of the process name mismatches)

I added a monkeypatch locally to just strip the cmdline but looks like every test relies on this working right as well so that didn't seem like much of a solution (was going to attach a pull request with this .. but it seems like a bigger mess)

**Comment by oz** [comment]
On Mac OS, `Sys::Proctable` does sysctl calls to get the list of processes, and replaces string terminators (`\0`) by spaces [in some occasions](https://github.com/djberg96/sys-proctable/blob/master/ext/darwin/sys/proctable.c). I didn't read all of it as I am a little busy elsewhere today, but this seems to be a good candidate.

This space-padding seem to appear with programs that change their process names (for example, foreman), so there could be an rstrip-based workaround with a proxy-class in Sponges, or better, a bug fix on sys-proctable's code.

HTH.

**Comment by piotrb** [comment]
yep it looks like a mess .. just wanted it fixed upstream so I don't have to have monkey patches in my code dealing with it .. the law of demeter prevents me touching the gem's upstream ;) I only know how to communicate with first level dependancies ;)

**Comment by chatgris** [comment]
I agree with @oz , this should be fixed in sys-proctable's code.

And, since I don't have any Mac OS around me, I can't help to provides a temporary fix in Sponges, or [machine](https://github.com/chatgris/machine) (which is a proxy around sys-proctable used behind the scene by sponges). 

Pull-request are welcomed. :smile:

**Comment by chatgris** [comment]
Since, it's not a Sponges bug, I close this issue.
