### ISSUE TITLE
Add support for specifying the stop signal (or change default to term)

### ISSUE THREAD

**Issue by piotrb** [af83/sponges#5]
I'd love for there to be a way to easily influence the signal sent at stop, right now it seems to be a choice between sigquit and sighup .. quit is quite brutal, if anything it should be sigterm, is not a common process management signal for many utilities, term is normally considered to be a much more graceful "ask the program to terminate", while quit is just an order to die. (also sigquit is meant to create core dumps, its generally not a good singal to use in an automated lifecycle)

If you can change from quit to term, that would satisfy this, or if not, just made an option in config allow to override the signal send on stop.

**Comment by chatgris** [comment]
Hi,

You can also use `HUP`, check out this example: https://github.com/AF83/sponges/blob/master/examples/pids.rb.

Basically, I tried to have a semantic on Signals close to [the one](http://unicorn.bogomips.org/SIGNALS.html) in Unicorn.

Nevertheless, I am not against changing this semantic in a future major version of sponges.

**Comment by piotrb** [comment]
I'm just saying that having this not configurable makes sponges not very viable .. I was looking into moving the currently fussy DelayedJob spawning code from a multi process mess to sponges managed group .. but without better control over the signals I can't do that.

DJ's QUIT will make the process die without finishing the running job, TERM will wait for it to finish, and thats a huge deal.

**Comment by chatgris** [comment]
Ok, I've got you this time.

Yes, it could totally be done. I will look into it by the end of the week.

**Comment by chatgris** [comment]
@piotrb I just added the ability to rewrites signals on the branch `rewrites_signals`, does this fix your issue ?

If so, I will merge it on master, and release a new version.

**Comment by chatgris** [comment]
@piotrb It is ok for you ?

**Comment by piotrb** [comment]
Hmm .. I don't really see how this is supposed to work .. 

``` ruby
          INT:  :INT,
          QUIT: :QUIT,
          TERM: :TERM,
          HUP:  :HUP,
          TTIN: :TTIN,
          TTOU: :TTOU,
          CHLD: :CHLD
```

Are you meant to re-map what the signals do? Like if you wanted to terminate with a TERM instead of a QUIT .. you'd re-map QUIT: :TERM ?

**Comment by piotrb** [comment]
if thats the case .. seems a bit odd .. I'd maybe see this more of being mapped based on function .. eg

``` ruby
{
  restart: :HUP,
  terminate: :QUIT,
  ... etc
}
```

Otherwise you need to have very intimate knowledge of how sponges uses its signals, to know you have to re-map quit to be term or whatnot.

**Comment by chatgris** [comment]
It's true, with a mapping on signals, a knowledge of how sponges uses its signals is mandatory. It could be easily provided by documentation though.

Anyway, I'm still thinking that signals should be keys.

More like, when the x signal comes in, what should happens. Maybe something like:

``` ruby
{
  INT:  :terminate,
  QUIT: :quit,
  TERM: :terminate,
  HUP:  :gracefully_quit,
  TTIN: :increase,
  TTOU: :decrease,
  CHLD: :restart_child
}
```

Still haven't made my mind of this. :frowning:

**Comment by piotrb** [comment]
Think you have the right idea, but perhaps backwards .. 

``` ruby
{
  terminate: :INT,
  quit: :QUIT,
  terminate: :TERM,
  gracefully_quit: :HUP,
  increase: :TTIN,
  decrease: :TTOU,
  restart_child: :CHLD,
}
```

This way you're mapping the intended use, with which singal to use for it, if someone decides they want to use TERM to quit the app .. all they have to do is

`signals[:quit] = :TERM`

and they're done
